### ISSUE TITLE
Usage Parsing Example fails

### ISSUE THREAD

**Issue by MAKOMO** [pretix/python-drafthorse#10]
In v2.3.0 and current trunk the example in [README.rst](https://github.com/pretix/python-drafthorse/blob/master/README.rst) fails

```python
>>> from drafthorse.models.document import Document
>>> samplexml = open("sample.xml", "rb").read()
>>> doc = Document.parse(samplexml)
>>> print(doc.trade.agreement.seller.name)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/drafthorse/models/elements.py", line 134, in __str__
    return str(self.text)
               ^^^^^^^^^
AttributeError: 'StringElement' object has no attribute 'text'. Did you mean: '_text'?```

**Comment by MAKOMO** [comment]
Fixed by Commit 78b360d4874cb86557c9b8335a33cf51aa80b957
